/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CmbjsToggle {
    'offCaption': string;
    'onCaption': string;
  }
  interface CmbjsToggleAttributes extends StencilHTMLAttributes {
    'offCaption'?: string;
    'onCaption'?: string;
    'onToggled'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CmbjsToggle': Components.CmbjsToggle;
  }

  interface StencilIntrinsicElements {
    'cmbjs-toggle': Components.CmbjsToggleAttributes;
  }


  interface HTMLCmbjsToggleElement extends Components.CmbjsToggle, HTMLStencilElement {}
  var HTMLCmbjsToggleElement: {
    prototype: HTMLCmbjsToggleElement;
    new (): HTMLCmbjsToggleElement;
  };

  interface HTMLElementTagNameMap {
    'cmbjs-toggle': HTMLCmbjsToggleElement
  }

  interface ElementTagNameMap {
    'cmbjs-toggle': HTMLCmbjsToggleElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
